name: Test CKAN core
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * 2,4'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    container:
      image: openknowledge/ckan-dev:master
    services:
      solr:
        image: ckan/ckan-solr:master
      postgres:
        image: ckan/ckan-postgres-dev:master
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
      redis:
          image: redis:3
    env:
      CKAN_SQLALCHEMY_URL: postgresql://ckan_default:pass@postgres/ckan_test
      CKAN_DATASTORE_WRITE_URL: postgresql://datastore_write:pass@postgres/datastore_test
      CKAN_DATASTORE_READ_URL: postgresql://datastore_read:pass@postgres/datastore_test
      CKAN_SOLR_URL: http://solr:8983/solr/ckan
      CKAN_REDIS_URL: redis://redis:6379/1

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/checkout@v3
    - name: Clone extension
      run: |
        git clone https://github.com/ckan/ckanext-archiver.git
    - name: Install dependencies
      run: |
        cd ckan
        pip install -r requirement-setuptools.txt
        pip install -r requirements.txt
        pip install -r dev-requirements.txt
        python setup.py develop
        pip check
    - name: Execute test
      run: |
        cd ckan
        pytest --ckan-ini=test-core.ini ckan/tests ckanext/
